const systemsKnowledge = {
  overview: {
    philosophy:
      "JB’s systems are designed to help people reduce chaos, rebuild structure, and make consistent action easier through systems instead of relying purely on motivation or willpower.",

    intent:
      "The focus is practical execution, self-awareness, and building environments and routines that support consistency over time.",

    framingNotes: [
      "The systems are built around practical execution rather than empty motivation.",

      "They are designed to support people who feel stuck, inconsistent, distracted, overwhelmed, or lacking structure.",

      "Different systems address different areas, including daily planning, broader life structure, and fitness progression.",

      "The goal is progress through repeated action, not perfection.",

      "Users should choose the system that most closely matches the problem they are currently trying to solve.",
    ],
  },

  systems: [
    {
      name: "The Routine",

      status: "available",

      type: "Interactive daily planning tool",

      purpose:
        "An interactive daily planning tool designed to help users build a structured day in under two minutes using their schedule, priorities, goals, and preferred activities.",

      whoItsFor: [
        "People who struggle to structure their day",

        "People who feel overwhelmed by competing priorities",

        "People who want to make time for focused work, fitness, meals, and recovery",

        "People who want a simple daily plan without manually organizing every time block",

        "People who need help turning priorities and commitments into a usable schedule",
      ],

      howItWorks: [
        "Users enter information such as their wake time, bedtime, daily goal, priorities, and existing commitments",

        "Users select which activities they want included, such as meals, workouts, deep work, breaks, and a wind-down period",

        "The tool organizes the information into a chronological daily plan",

        "The generated plan includes scheduled blocks, priorities, commitments, and a daily summary",

        "Users can review and print the generated plan",
      ],

      whatItIs: [
        "A browser-based daily planning tool",

        "A fast way to organize priorities and commitments",

        "A system for turning user-entered information into a structured schedule",

        "A tool designed to reduce decision fatigue and planning friction",

        "A daily execution tool rather than a long-term program",
      ],

      keyFeatures: [
        "Builds a day around wake time and bedtime",

        "Accounts for fixed commitments",

        "Includes up to three daily priorities",

        "Can include meals, workouts, deep work, breaks, and wind-down time",

        "Adjusts the schedule around existing time conflicts",

        "Generates a chronological daily plan",

        "Provides a summary of the planned day",

        "Supports printing the completed routine",
      ],

      whatItIsNot: [
        "A long-term habit program",

        "A guarantee that every task will be completed",

        "A medical, therapeutic, or professional scheduling service",

        "A replacement for the user making decisions about their own health, workload, or responsibilities",

        "A plan Bands can generate directly inside the conversation",
      ],

      connections: [
        "Supports JB’s systems-first approach to discipline and execution",

        "Can be used alongside the 30 Day Reset to structure individual days",

        "Can help users organize training generated by The 10 Week Build",

        "Connects with Improving JB content related to focus, consistency, discipline, and reducing friction",
      ],

      access: {
        route: "/systems/routine",

        note:
          "Only provide the exact website route when it is included and confirmed in the knowledge base.",
      },
    },

    {
      name: "30 Day Reset",

      status: "available",

      type: "Short-term structure and consistency system",

      purpose:
        "A 30-day system designed to help users reset routines, rebuild structure, and focus on consistent daily execution.",

      whoItsFor: [
        "People who feel stuck or inconsistent",

        "People trying to regain discipline and structure",

        "People overwhelmed by distractions, bad habits, or lack of direction",

        "People who want a simple short-term system focused on execution",

        "People who need a defined period to reset their behavior and priorities",
      ],

      howItWorks: [
        "Users follow a structured framework across 30 days",

        "The system encourages users to identify priorities and non-negotiable actions",

        "Users track daily execution and become more aware of patterns, mistakes, and consistency",

        "The focus is continuing after imperfect days rather than abandoning the reset",

        "The system provides external structure while the user works to rebuild internal consistency",
      ],

      whatItIs: [
        "A structured 30-day reset framework",

        "A system centered around non-negotiables and daily execution",

        "A short-term reset focused on consistency and awareness",

        "A framework that expects mistakes and focuses on continuing forward instead of being perfect",

        "A tool for helping users organize priorities and reduce chaos",
      ],

      keyFeatures: [
        "A defined 30-day timeframe",

        "Daily structure and execution tracking",

        "A focus on non-negotiable actions",

        "Space for priorities, reflection, or awareness",

        "A restart-oriented approach that does not require perfection",

        "A practical framework for rebuilding momentum",
      ],

      whatItIsNot: [
        "A motivational gimmick",

        "A replacement for therapy, treatment, or professional help",

        "A guaranteed transformation",

        "A magic productivity fix",

        "A personalized medical, fitness, or mental-health program",
      ],

      connections: [
        "Connected to JB’s content around discipline, consistency, distractions, addictions, and self-control",

        "Built around JB’s systems-first philosophy",

        "Designed to complement the broader Improving JB ecosystem",

        "Can be used with The Routine to create structure for individual days",

        "Can support consistent execution of a fitness program such as The 10 Week Build",
      ],

      access: {
        route: "/systems/reset",

        externalUrl: null,

        note:
          "Only provide an access route or download link when the exact confirmed link exists in the knowledge base.",
      },
    },

    {
      name: "The 10 Week Build",

      status: "available",

      type: "Personalized strength and fitness progression system",

      purpose:
        "A personalized 10-week training system designed to help users build strength, improve consistency, and work toward stronger performance through structured progression.",

      whoItsFor: [
        "People looking for more structure in the gym",

        "People who want a personalized training plan",

        "People focused on improving squat, bench press, and deadlift strength",

        "People trying to build discipline through consistent training",

        "People training with full gym access, dumbbells, or bodyweight equipment",

        "People who want a defined progression rather than choosing workouts day by day",
      ],

      howItWorks: [
        "Users enter details such as experience level, goal, training frequency, workout length, equipment access, and current squat, bench press, and deadlift maxes",

        "The system generates a 10-week program based on those inputs",

        "The program uses structured progression across the training weeks",

        "Recommended training weights are calculated from the information the user provides",

        "The completed program can be downloaded as an Excel file for tracking",
      ],

      whatItIs: [
        "A custom-generated 10-week workout program",

        "A progression-based strength system",

        "A program built around current squat, bench press, and deadlift maxes",

        "A structured framework designed to improve training consistency and performance",

        "A system that adapts based on training frequency, goals, experience level, workout length, and equipment access",

        "A downloadable program that can be exported as an Excel file",
      ],

      keyFeatures: [
        "Supports 3, 4, 5, and 6-day training schedules",

        "Supports full-gym, dumbbell, and home or bodyweight training options",

        "Generates recommended workout weights using user-entered maxes",

        "Includes progressive overload across 10 weeks",

        "Provides strength targets based on current performance",

        "Accounts for the user's goal and experience level",

        "Accounts for the amount of time available for each workout",

        "Exports directly to Excel for tracking and execution",
      ],

      whatItIsNot: [
        "A guaranteed body or strength transformation",

        "A replacement for medical guidance or qualified professional coaching",

        "A one-size-fits-all workout template",

        "A shortcut to results without consistent effort",

        "A rehabilitation or injury-treatment program",
      ],

      connections: [
        "Built around JB’s systems-first philosophy",

        "Designed to complement Improving JB content related to discipline, fitness, consistency, and self-improvement",

        "Can be used alongside the 30 Day Reset to support broader consistency",

        "Can be placed into The Routine to organize training around the user’s other daily commitments",
      ],

      access: {
        route: "/systems/build",

        note:
          "Only provide the exact website route when it is included and confirmed in the knowledge base.",
      },
    },
  ],

  comparisonGuidance: {
    generalRules: [
      "Recommend The Routine when the user mainly needs help organizing a single day.",

      "Recommend the 30 Day Reset when the user wants a broader short-term structure for rebuilding discipline and consistency.",

      "Recommend The 10 Week Build when the user primarily wants a structured strength-training program.",

      "The systems can complement one another, but do not recommend all of them unless the user’s question genuinely involves multiple needs.",

      "Explain the strongest match first and briefly state why it fits.",
    ],

    examples: [
      {
        userNeed: "I never know how to organize everything I need to do today.",

        recommendedSystem: "The Routine",
      },

      {
        userNeed: "I have been inconsistent for months and need a reset.",

        recommendedSystem: "30 Day Reset",
      },

      {
        userNeed: "I want a structured plan to increase my main lifts.",

        recommendedSystem: "The 10 Week Build",
      },
    ],
  },

  futureSystems: {
    status: "not publicly confirmed",

    systems: [],

    notes: [
      "Additional systems, programs, and upgrades may be added in future versions of Improving JB.",

      "Do not name, describe, price, or promise unreleased systems unless they are intentionally added to the public knowledge base.",

      "Internal development ideas are not the same as publicly available or officially announced products.",
    ],
  },

  guardrails: {
    truthPolicy: [
      "Do not promise transformations or guaranteed outcomes.",

      "Do not customize systems beyond the customization features that officially exist.",

      "Do not invent features, templates, routes, prices, downloads, or systems that are not provided in the knowledge base.",

      "Do not explain step-by-step implementation unless that information exists in the provided knowledge.",

      "Do not claim to generate, save, print, export, purchase, or download anything on the user’s behalf.",

      "Do not present an unreleased system or upgrade as available.",

      "Do not treat JB’s systems as substitutes for professional medical, therapeutic, legal, or financial services.",
    ],

    allowedHelp: [
      "Explain what each system is",

      "Explain who a system is generally designed for",

      "Explain how a system works using confirmed information",

      "Compare existing Improving JB systems",

      "Recommend the most relevant existing system based on the user’s stated need",

      "Explain how systems connect to JB’s content and philosophy",

      "Help users understand where systems fit into the broader ecosystem",

      "Direct users to where systems can be accessed when the exact route or link is provided",
    ],
  },
};

export default systemsKnowledge;